<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { api, date, level, send } from '../api'
import { useSession } from '../store'
type Notification = { id:number; kind:string; message:string; post_id:number|null; is_read:boolean; created_at:string }
const route=useRoute(), session=useSession(), tab=ref(route.path.includes('notifications')?'notifications':'profile'), favorites=ref<any[]>([]), logs=ref<any[]>([]), notifications=ref<Notification[]>([]), publicUser=ref<any>(), error=ref(''), notificationError=ref(''), saved=ref('')
const mine=computed(() => !route.params.id)
const profile=ref({school:'',grade:'',major:'',subjectPreference:'',publicSchool:false,publicGrade:false})
onMounted(async () => { if (!mine.value) { publicUser.value=await api('/users/'+route.params.id); return } await session.refresh(); const user=session.user; if (!user) return; profile.value={school:user.school || '',grade:user.grade || '',major:user.major || '',subjectPreference:user.subject_preference || '',publicSchool:user.public_school,publicGrade:user.public_grade}; await reloadNotifications(); [favorites.value,logs.value]=await Promise.all([api('/me/favorites').catch(() => []),api('/me/point-logs').catch(() => [])]) })
watch(() => route.path, path => { tab.value=path.includes('notifications')?'notifications':'profile'; if (tab.value==='notifications') reloadNotifications() })
async function reloadNotifications() { try { const result=await api<{items:Notification[],unread:number}>('/notifications'); notifications.value=result.items; session.unread=result.unread; notificationError.value='' } catch (exception) { notificationError.value=(exception as Error).message } }
async function readNotification(item:Notification) { if (!item.is_read) { try { await send('/notifications/'+item.id+'/read','PATCH'); item.is_read=true; session.unread=Math.max(0,session.unread-1) } catch (exception) { notificationError.value=(exception as Error).message } } }
function notificationKind(kind:string) { return ({system:'系统公告',report:'举报处理结果',reply:'帖子回复',accepted:'回答被采纳',featured:'帖子加精'} as Record<string,string>)[kind] || '通知' }
async function save() { try { await send('/me/profile','PUT',profile.value); await session.refresh(); saved.value='资料已保存' } catch (exception) { error.value=(exception as Error).message } }
async function readAll() { try { await send('/notifications/read-all','POST'); await reloadNotifications() } catch (exception) { notificationError.value=(exception as Error).message } }
</script>
<template><div class="content-page"><div v-if="!mine && publicUser"><div class="profile-hero"><span class="profile-avatar">{{ publicUser.username[0] }}</span><div><h1>{{ publicUser.username }}</h1><p>{{ publicUser.school }} {{ publicUser.grade }}</p><span>Lv{{ publicUser.points>=1000?5:publicUser.points>=500?4:publicUser.points>=200?3:publicUser.points>=50?2:1 }} {{ level(publicUser.points) }} · {{ publicUser.points }} 积分</span></div></div></div><template v-else-if="session.user"><div class="page-heading"><span>个人空间</span><h1>你好，{{ session.user.username }}</h1><p>记录你的学习足迹，管理你关注的讨论。</p></div><div class="profile-summary"><span class="profile-avatar">{{ session.user.username[0] }}</span><div><strong>{{ session.user.username }}</strong><span>Lv{{ session.user.points>=1000?5:session.user.points>=500?4:session.user.points>=200?3:session.user.points>=50?2:1 }} {{ level(session.user.points) }}</span></div><div class="points-num">{{ session.user.points }}<small>当前积分</small></div></div><div class="tabs"><button v-for="item in [{id:'profile',name:'个人资料'},{id:'favorites',name:'我的收藏'},{id:'notifications',name:'通知'},{id:'points',name:'积分明细'}]" :key="item.id" :class="{active:tab===item.id}" @click="tab=item.id">{{ item.name }}<span v-if="item.id==='notifications' && session.unread"> {{ session.unread }}</span></button></div>
  <form v-if="tab==='profile'" class="profile-form" @submit.prevent="save"><div class="form-row"><label>学校<input v-model="profile.school" maxlength="100" placeholder="你的学校"/></label><label>年级<input v-model="profile.grade" maxlength="40" placeholder="例如 大二"/></label></div><div class="form-row"><label>专业 / 班级<input v-model="profile.major" maxlength="100"/></label><label>学科偏好<input v-model="profile.subjectPreference" maxlength="100"/></label></div><label class="check"><input v-model="profile.publicSchool" type="checkbox"/> 公开学校</label><label class="check"><input v-model="profile.publicGrade" type="checkbox"/> 公开年级</label><button class="button primary">保存资料</button><span class="success">{{ saved }}</span></form>
  <div v-if="tab==='favorites'" class="account-list"><div v-if="!favorites.length" class="empty">还没有收藏，遇到好内容记得保存。</div><RouterLink v-for="item in favorites" :key="item.id" :to="'/posts/'+item.id"><strong>{{ item.title }}</strong><span>{{ item.board_name }} · {{ date(item.created_at) }}</span></RouterLink></div>
  <div v-if="tab==='notifications'" class="account-list"><button v-if="notifications.length" class="subtle-action" @click="readAll">全部标记已读</button><p v-if="notificationError" class="error">通知加载失败：{{ notificationError }} <button type="button" @click="reloadNotifications">重试</button></p><div v-else-if="!notifications.length" class="empty">暂时没有新消息。</div><article v-for="item in notifications" :key="item.id" class="notification-item" :class="{unread:!item.is_read}"><div><span class="notification-kind">{{ notificationKind(item.kind) }}</span><span class="notification-date">{{ date(item.created_at) }}</span></div><p>{{ item.message }}</p><div class="notification-actions"><RouterLink v-if="item.post_id" :to="'/posts/'+item.post_id" @click="readNotification(item)">查看帖子</RouterLink><button v-if="!item.is_read" type="button" @click="readNotification(item)">标记已读</button></div></article></div>
  <div v-if="tab==='points'" class="account-list"><div v-if="!logs.length" class="empty">还没有积分记录。</div><div v-for="item in logs" :key="item.id" class="log-row"><span>{{ {register:'注册',login:'每日登录',post:'发帖',reply:'回帖',accepted:'回答被采纳',featured:'帖子加精',report_valid:'有效举报',adjust:'管理员调整'}[item.action as 'post'] || item.action }}<small>{{ date(item.created_at) }}</small></span><strong>{{ item.points>0?'+':'' }}{{ item.points }}</strong></div></div><p v-if="error" class="error">{{ error }}</p></template></div></template>
