<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api, send, type Board, type Tag } from '../api'
import { useSession } from '../store'
const route=useRoute(), router=useRouter(), session=useSession(), section=computed(() => String(route.params.section || 'dashboard'))
const dashboard=ref<any>({}), users=ref<any[]>([]), posts=ref<any[]>([]), reports=ref<any[]>([]), boards=ref<Board[]>([]), tags=ref<Tag[]>([]), logs=ref<any[]>([]), announcement=ref(''), error=ref('')
const sections=[['dashboard','概览'],['reports','举报处理'],['posts','内容管理'],['users','用户管理'],['boards','板块与标签'],['points','操作记录'],['announcements','系统公告']]
async function load() { if (!session.user || !['admin','moderator'].includes(session.user.role)) return; try { [dashboard.value,reports.value,posts.value,boards.value,tags.value]=await Promise.all([api('/admin/dashboard'),api('/admin/reports'),api('/admin/posts'),api('/boards'),api('/tags')]); if (session.user.role==='admin') { users.value=await api('/admin/users'); logs.value=await api('/admin/points') } } catch (exception) { error.value=(exception as Error).message } }
onMounted(load); watch(section,load)
async function change(path:string,method:string,value:object) { try { await send(path,method,value); ElMessage.success('操作已完成'); await load() } catch (exception) { ElMessage.error((exception as Error).message) } }
async function process(report:any,action:string) { const result=await ElMessageBox.prompt('填写处理备注（可留空）','处理举报',{inputValue:''}).catch(() => null); if (result) change(`/admin/reports/${report.id}`,'PATCH',{action,note:result.value}) }
async function addBoard() { const result=await ElMessageBox.prompt('请输入板块名称','新增板块').catch(() => null); if (!result) return; const slug='board-'+Date.now(); change('/admin/boards','POST',{name:result.value,slug,description:'学习交流板块'}) }
async function addTag() { const result=await ElMessageBox.prompt('请输入标签名称','新增标签').catch(() => null); if (result) change('/admin/tags','POST',{name:result.value}) }
async function adjust(user:any) { const result=await ElMessageBox.prompt('输入积分增减数值','调整积分').catch(() => null); if (result) change(`/admin/users/${user.id}/points`,'POST',{amount:Number(result.value)}) }
</script>
<template><div class="admin-page" v-if="session.user && ['admin','moderator'].includes(session.user.role)"><div class="page-heading"><span>社区治理</span><h1>管理后台</h1><p>保持讨论有序，让每一份认真回答被看见。</p></div><div class="admin-tabs"><RouterLink v-for="item in sections.filter(item=>session.user?.role==='admin' || !['users','boards','points','announcements'].includes(item[0]))" :key="item[0]" :to="item[0]==='dashboard'?'/admin':'/admin/'+item[0]" :class="{active:section===item[0]}">{{ item[1] }}</RouterLink></div><p v-if="error" class="error">{{ error }}</p>
  <div v-if="section==='dashboard'" class="stats-grid"><div v-for="item in [['用户',dashboard.users],['帖子',dashboard.posts],['回复',dashboard.replies],['今日新帖',dashboard.today],['待处理举报',dashboard.pending]]" :key="item[0]"><strong>{{ item[1] ?? '—' }}</strong><span>{{ item[0] }}</span></div></div>
  <template v-if="section==='reports'"><h2>举报队列</h2><el-table :data="reports" stripe><el-table-column prop="id" label="ID" width="65"/><el-table-column prop="reporter_name" label="举报人" width="110"/><el-table-column prop="target_type" label="对象" width="90"/><el-table-column prop="target_id" label="对象 ID" width="90"/><el-table-column prop="reason" label="原因"/><el-table-column prop="status" label="状态"/><el-table-column label="处理" min-width="260"><template #default="scope"><template v-if="scope.row.status==='pending'"><el-button size="small" @click="process(scope.row,'reject')">驳回</el-button><el-button size="small" @click="process(scope.row,'hide')">隐藏</el-button><el-button size="small" type="danger" @click="process(scope.row,'delete')">删除</el-button><el-button v-if="session.user?.role==='admin'" size="small" @click="process(scope.row,'mute')">禁言</el-button></template><span v-else>{{ scope.row.handle_note }}</span></template></el-table-column></el-table></template>
  <template v-if="section==='posts'"><h2>内容管理</h2><el-table :data="posts" stripe><el-table-column prop="title" label="帖子" min-width="220"/><el-table-column prop="username" label="作者" width="100"/><el-table-column prop="status" label="状态" width="90"/><el-table-column label="操作" min-width="240"><template #default="scope"><el-button size="small" @click="change(`/admin/posts/${scope.row.id}/feature`,'PATCH',{featured:!scope.row.is_featured})">{{ scope.row.is_featured?'取消精华':'加精' }}</el-button><el-button size="small" @click="change(`/admin/posts/${scope.row.id}/top`,'PATCH',{top:!scope.row.is_top})">{{ scope.row.is_top?'取消置顶':'置顶' }}</el-button><el-button size="small" @click="change(`/admin/posts/${scope.row.id}/status`,'PATCH',{status:scope.row.status==='published'?'hidden':'published'})">{{ scope.row.status==='published'?'隐藏':'恢复' }}</el-button></template></el-table-column></el-table></template>
  <template v-if="section==='users'"><h2>用户管理</h2><el-table :data="users" stripe><el-table-column prop="username" label="昵称"/><el-table-column prop="email" label="邮箱" min-width="180"/><el-table-column prop="role" label="角色"/><el-table-column prop="status" label="状态"/><el-table-column prop="points" label="积分"/><el-table-column label="操作" min-width="220"><template #default="scope"><el-button size="small" @click="change(`/admin/users/${scope.row.id}/status`,'PATCH',{status:scope.row.status==='active'?'muted':'active'})">{{ scope.row.status==='active'?'禁言':'解除' }}</el-button><el-button size="small" @click="adjust(scope.row)">积分</el-button></template></el-table-column></el-table></template>
  <template v-if="section==='boards'"><div class="section-heading"><h2>板块</h2><el-button @click="addBoard">新增板块</el-button></div><div class="admin-list"><div v-for="item in boards" :key="item.id"><strong>{{ item.name }}</strong><span>{{ item.description }}</span></div></div><div class="section-heading"><h2>标签</h2><el-button @click="addTag">新增标签</el-button></div><div class="tag-cloud"><span v-for="item in tags" :key="item.id"># {{ item.name }}</span></div></template>
  <template v-if="section==='points'"><h2>管理操作记录</h2><div class="admin-list"><div v-for="item in logs" :key="item.id"><strong>{{ item.action }}</strong><span>{{ item.target_type }} #{{ item.target_id }} · {{ item.detail }}</span></div></div></template>
  <template v-if="section==='announcements'"><h2>发布系统公告</h2><textarea v-model="announcement" rows="5" maxlength="255" placeholder="公告内容将发送给所有用户"/><button class="button primary" @click="async () => { await change('/admin/announcements','POST',{message:announcement}); announcement='' }">发布公告</button></template>
  </div><div v-else class="empty">此页面仅供版主和管理员使用。</div></template>
