<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { api, send, upload, type Board, type Post, type Tag } from '../api'
const router=useRouter(), boards=ref<Board[]>([]), tags=ref<Tag[]>([]), boardId=ref<number>(), type=ref('question'), title=ref(''), content=ref(''), selected=ref<number[]>([]), image=ref(''), error=ref(''), busy=ref(false)
onMounted(async () => { [boards.value,tags.value]=await Promise.all([api('/boards'),api('/tags')]); boardId.value=boards.value[0]?.id })
async function addImage(event: Event) { const file=(event.target as HTMLInputElement).files?.[0]; if (file) try { image.value=(await upload(file)).path } catch (exception) { error.value=(exception as Error).message } }
async function publish() { busy.value=true; error.value=''; try { const post=await send<Post>('/posts','POST',{ boardId:boardId.value,type:type.value,title:title.value,content:content.value,tagIds:selected.value,imagePath:image.value || null }); router.push('/posts/'+post.id) } catch (exception) { error.value=(exception as Error).message } finally { busy.value=false } }
</script>
<template><div class="content-page"><div class="page-heading"><span>分享你的思考</span><h1>发布新帖子</h1><p>清晰地描述问题或经验，让交流更有收获。</p></div><form class="compose-form" @submit.prevent="publish"><div class="form-row"><label>选择板块<select v-model="boardId" required><option v-for="board in boards" :value="board.id" :key="board.id">{{ board.name }}</option></select></label><label>帖子类型<select v-model="type"><option value="question">问答 · 寻求解答</option><option value="discussion">讨论 · 交流观点</option><option value="experience">经验 · 分享方法</option></select></label></div><label>标题<input v-model="title" required minlength="5" maxlength="160" placeholder="一句话说清楚你想讨论什么"/></label><label>正文<textarea v-model="content" required minlength="10" rows="12" placeholder="补充背景、你的尝试或具体问题…"/></label><label>添加标签<span class="tag-options"><button v-for="tag in tags" :key="tag.id" type="button" :class="{selected:selected.includes(tag.id)}" @click="selected=selected.includes(tag.id)?selected.filter(id=>id!==tag.id):[...selected,tag.id]"># {{ tag.name }}</button></span></label><label class="upload-label">添加图片<input type="file" accept="image/png,image/jpeg,image/webp" @change="addImage"/><small>支持 JPG、PNG、WebP，最大 5MB</small></label><img v-if="image" :src="image" class="image-preview" alt="上传预览"/><p v-if="error" class="error">{{ error }}</p><div class="form-actions"><RouterLink to="/">取消</RouterLink><button class="button primary" :disabled="busy">{{ busy?'发布中…':'发布帖子' }}</button></div></form></div></template>
