<script setup lang="ts">
import { onMounted, onUnmounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { api, send, upload, type Board, type Post, type Tag } from '../api'
const router=useRouter(), route=useRoute(), boards=ref<Board[]>([]), tags=ref<Tag[]>([]), boardId=ref<number>(), type=ref('question'), title=ref(''), content=ref(''), selected=ref<number[]>([]), image=ref(''), error=ref(''), busy=ref(false), draftId=ref<number>(), saved=ref(''), scheduled=ref(''), voteOptions=ref(''), multiple=ref(false), visibility=ref('always'), closesAt=ref(''), bounty=ref(0), attachment=ref(''), cover=ref('')
let autosave: ReturnType<typeof setInterval> | undefined
onMounted(async () => { [boards.value,tags.value]=await Promise.all([api('/boards'),api('/tags')]); boardId.value=boards.value[0]?.id; const id=Number(route.query.draft); if (id) { const draft=await api<any>('/drafts/'+id); if (draft) { draftId.value=id; boardId.value=draft.board_id || boardId.value; type.value=draft.type; title.value=draft.title; content.value=draft.content; image.value=draft.image_path || ''; selected.value=draft.tag_ids?.split(',').map(Number).filter(Boolean) || []; scheduled.value=draft.scheduled_at ? String(draft.scheduled_at).slice(0,16) : ''; cover.value=draft.cover_path || ''; attachment.value=draft.attachment_path || '' } } autosave=setInterval(() => { if (title.value || content.value) saveDraft(true) },15000) })
onUnmounted(() => { if (autosave) clearInterval(autosave) })
async function saveDraft(silent=false) { try { const data={boardId:boardId.value,type:type.value,title:title.value,content:content.value,imagePath:image.value || null,tagIds:selected.value.join(','),coverPath:cover.value || null,attachmentPath:attachment.value || null,scheduledAt:scheduled.value || null}; if (draftId.value) await send('/drafts/'+draftId.value,'PATCH',data); else { const draft=await send<{id:number}>('/drafts','POST',data); draftId.value=draft.id } if (!silent) saved.value='草稿已保存'; return true } catch (exception) { if (!silent) error.value=(exception as Error).message; return false } }
function insertSyntax(prefix:string,suffix='') { const field=document.querySelector<HTMLTextAreaElement>('.compose-form textarea'); const start=field?.selectionStart ?? content.value.length, end=field?.selectionEnd ?? start; const selected=content.value.slice(start,end); content.value=content.value.slice(0,start)+prefix+selected+suffix+content.value.slice(end); requestAnimationFrame(() => { field?.focus(); field?.setSelectionRange(start+prefix.length,start+prefix.length+selected.length) }) }
async function addCover(event:Event) { const file=(event.target as HTMLInputElement).files?.[0]; if (file) try { cover.value=(await upload(file)).path } catch (exception) { error.value=(exception as Error).message } }
async function addAttachment(event:Event) { const file=(event.target as HTMLInputElement).files?.[0]; if (file) try { const form=new FormData(); form.append('file',file); attachment.value=(await api<{path:string}>('/attachments',{method:'POST',body:form})).path } catch (exception) { error.value=(exception as Error).message } }
async function addImage(event: Event) { const file=(event.target as HTMLInputElement).files?.[0]; if (file) try { image.value=(await upload(file)).path } catch (exception) { error.value=(exception as Error).message } }
async function publish() { busy.value=true; error.value=''; try { if (scheduled.value) { if (new Date(scheduled.value)<=new Date()) throw new Error('定时发布时间必须在未来'); if (await saveDraft()) router.push('/me/drafts'); return } const vote=voteOptions.value.trim()?{multiple:multiple.value,closesAt:closesAt.value,visibility:visibility.value,options:voteOptions.value.split(',').map(value=>value.trim()).filter(Boolean)}:null; const post=await send<Post>('/posts/enhanced','POST',{boardId:boardId.value,type:type.value,title:title.value,content:content.value,tagIds:selected.value,imagePath:image.value || null,attachmentPath:attachment.value || null,coverPath:cover.value || null,vote,bounty:bounty.value}); if (draftId.value) await send('/drafts/'+draftId.value,'DELETE'); router.push('/posts/'+post.id) } catch (exception) { error.value=(exception as Error).message } finally { busy.value=false } }
</script>
<template><div class="content-page"><div class="page-heading"><span>分享你的思考</span><h1>发布新帖子</h1><p>清晰地描述问题或经验，让交流更有收获。</p></div><form class="compose-form" @submit.prevent="publish"><div class="form-row"><label>选择板块<select v-model="boardId" required><option v-for="board in boards" :value="board.id" :key="board.id">{{ board.name }}</option></select></label><label>帖子类型<select v-model="type"><option value="question">问答 · 寻求解答</option><option value="discussion">讨论 · 交流观点</option><option value="experience">经验 · 分享方法</option></select></label></div><label>标题<input v-model="title" required minlength="5" maxlength="160" placeholder="一句话说清楚你想讨论什么"/></label><div class="v2-editor-toolbar"><button type="button" @click="insertSyntax('# ')">标题</button><button type="button" @click="insertSyntax('\n' + String.fromCharCode(96,96,96) + '\n','\n' + String.fromCharCode(96,96,96) + '\n')">代码块</button><button type="button" @click="insertSyntax('\n' + String.fromCharCode(36,36) + '\n','\n' + String.fromCharCode(36,36) + '\n')">公式</button><span>使用 @昵称 提及同学</span></div><label>正文<textarea v-model="content" required minlength="10" rows="12" placeholder="补充背景、你的尝试或具体问题…"/></label><label>添加标签<span class="tag-options"><button v-for="tag in tags" :key="tag.id" type="button" :class="{selected:selected.includes(tag.id)}" @click="selected=selected.includes(tag.id)?selected.filter(id=>id!==tag.id):[...selected,tag.id]"># {{ tag.name }}</button></span></label><label class="upload-label">添加图片<input type="file" accept="image/png,image/jpeg,image/webp" @change="addImage"/><small>支持 JPG、PNG、WebP，最大 5MB</small></label><img v-if="image" :src="image" class="image-preview" alt="上传预览"/><label class="upload-label">封面图<input type="file" accept="image/png,image/jpeg,image/webp" @change="addCover"/></label><img v-if="cover" :src="cover" class="image-preview" alt="封面预览"/><label class="upload-label">附件（PDF、TXT、ZIP，最多 5MB）<input type="file" accept=".pdf,.txt,.zip" @change="addAttachment"/></label><span v-if="attachment">附件已上传</span><label>定时发布<input v-model="scheduled" type="datetime-local"/></label><label>投票选项（逗号分隔）<input v-model="voteOptions" placeholder="选项 A, 选项 B"/></label><div v-if="voteOptions" class="form-row"><label>截止时间<input v-model="closesAt" type="datetime-local"/></label><label>结果可见<select v-model="visibility"><option value="always">随时可见</option><option value="after_vote">投票后可见</option><option value="after_close">截止后可见</option></select></label><label class="check"><input v-model="multiple" type="checkbox"/> 多选</label></div><label v-if="type==='question'">积分悬赏<input v-model.number="bounty" type="number" min="0" max="1000"/></label><p v-if="saved" class="success">{{ saved }}</p><p v-if="error" class="error">{{ error }}</p><div class="form-actions"><RouterLink to="/">取消</RouterLink><button type="button" class="button" @click="saveDraft()">保存草稿</button><button class="button primary" :disabled="busy">{{ busy?'发布中…':'发布帖子' }}</button></div></form></div></template>
