package com.studentforum;

import java.util.List;
import java.util.Map;
import org.apache.ibatis.annotations.*;

@Mapper
public interface ForumMapper {
    @Select("SELECT id,email,username,role,status,moderator_board_id,points,school,grade,major,subject_preference,public_school,public_grade,created_at FROM users WHERE id=#{id}") Map<String,Object> user(long id);
    @Select("SELECT id,password_hash,status,role FROM users WHERE email=#{email}") Map<String,Object> credentials(String email);
    @Select("SELECT COUNT(*) FROM users WHERE email=#{email} OR username=#{username}") int userExists(@Param("email") String email,@Param("username") String username);
    @Insert("INSERT INTO users(email,username,password_hash) VALUES(#{email},#{username},#{hash})") @Options(useGeneratedKeys=true,keyProperty="id") void insertUser(Map<String,Object> user);
    @Update("UPDATE users SET last_login_at=NOW() WHERE id=#{id}") void login(long id);
    @Update("UPDATE users SET school=#{school},grade=#{grade},major=#{major},subject_preference=#{subject},public_school=#{publicSchool},public_grade=#{publicGrade} WHERE id=#{id}") void profile(@Param("id") long id,@Param("school") String school,@Param("grade") String grade,@Param("major") String major,@Param("subject") String subject,@Param("publicSchool") boolean publicSchool,@Param("publicGrade") boolean publicGrade);
    @Update("UPDATE users SET password_hash=#{hash} WHERE id=#{id}") void password(@Param("id") long id,@Param("hash") String hash);
    @Select("SELECT password_hash FROM users WHERE id=#{id}") String hash(long id);
    @Select("SELECT id,name,slug,description,sort_order FROM boards WHERE status='enabled' ORDER BY sort_order,id") List<Map<String,Object>> boards();
    @Select("SELECT id,name FROM tags WHERE status='enabled' ORDER BY name") List<Map<String,Object>> tags();
    @Select("SELECT id,name FROM boards WHERE id=#{id} AND status='enabled'") Map<String,Object> board(long id);
    @Select("SELECT id,name FROM tags WHERE id=#{id} AND status='enabled'") Map<String,Object> tag(long id);
    @Select("SELECT p.*,u.username,u.points AS author_points,b.name AS board_name,(SELECT COUNT(*) FROM replies r WHERE r.post_id=p.id AND r.status='published') AS reply_count,(SELECT COUNT(*) FROM favorites f WHERE f.post_id=p.id) AS favorite_count FROM posts p JOIN users u ON u.id=p.author_id JOIN boards b ON b.id=p.board_id WHERE p.id=#{id}") Map<String,Object> post(long id);
    @Select("<script>SELECT p.id,p.board_id,p.author_id,p.type,p.title,p.content,p.image_path,p.is_solved,p.is_featured,p.is_top,p.view_count,p.created_at,u.username,b.name AS board_name,(SELECT COUNT(*) FROM replies r WHERE r.post_id=p.id AND r.status='published') AS reply_count FROM posts p JOIN users u ON u.id=p.author_id JOIN boards b ON b.id=p.board_id WHERE p.status='published' <if test='board != null'>AND p.board_id=#{board}</if><if test='tag != null'>AND EXISTS(SELECT 1 FROM post_tags pt WHERE pt.post_id=p.id AND pt.tag_id=#{tag})</if><if test='type != null'>AND p.type=#{type}</if><if test='solved != null'>AND p.is_solved=#{solved}</if><if test='featured != null'>AND p.is_featured=#{featured}</if><if test='keyword != null'>AND (p.title LIKE CONCAT('%',#{keyword},'%') OR p.content LIKE CONCAT('%',#{keyword},'%') OR EXISTS(SELECT 1 FROM post_tags pt JOIN tags t ON t.id=pt.tag_id WHERE pt.post_id=p.id AND t.name LIKE CONCAT('%',#{keyword},'%')))</if> ORDER BY p.is_top DESC <choose><when test='sort == &quot;hot&quot;'>, (p.view_count + (SELECT COUNT(*) FROM replies r WHERE r.post_id=p.id AND r.status='published') * 5) DESC</when><otherwise>, p.created_at DESC</otherwise></choose> LIMIT #{limit} OFFSET #{offset}</script>") List<Map<String,Object>> posts(@Param("board") Long board,@Param("tag") Long tag,@Param("type") String type,@Param("solved") Boolean solved,@Param("featured") Boolean featured,@Param("keyword") String keyword,@Param("sort") String sort,@Param("limit") int limit,@Param("offset") int offset);
    @Select("SELECT t.id,t.name FROM tags t JOIN post_tags pt ON pt.tag_id=t.id WHERE pt.post_id=#{postId}") List<Map<String,Object>> postTags(long postId);
    @Insert("INSERT INTO posts(board_id,author_id,type,title,content,image_path) VALUES(#{boardId},#{authorId},#{type},#{title},#{content},#{imagePath})") @Options(useGeneratedKeys=true,keyProperty="id") void insertPost(Map<String,Object> post);
    @Insert("INSERT IGNORE INTO post_tags(post_id,tag_id) VALUES(#{postId},#{tagId})") void postTag(@Param("postId") long postId,@Param("tagId") long tagId);
    @Update("UPDATE posts SET title=#{title},content=#{content} WHERE id=#{id}") void editPost(@Param("id") long id,@Param("title") String title,@Param("content") String content);
    @Update("UPDATE posts SET status=#{status} WHERE id=#{id}") void postStatus(@Param("id") long id,@Param("status") String status);
    @Update("UPDATE posts SET view_count=view_count+1 WHERE id=#{id}") void view(long id);
    @Select("SELECT r.*,u.username,u.points AS author_points FROM replies r JOIN users u ON u.id=r.author_id WHERE r.post_id=#{postId} AND r.status='published' ORDER BY r.is_accepted DESC,r.created_at") List<Map<String,Object>> replies(long postId);
    @Select("SELECT * FROM replies WHERE id=#{id}") Map<String,Object> reply(long id);
    @Insert("INSERT INTO replies(post_id,author_id,content,image_path) VALUES(#{postId},#{authorId},#{content},#{imagePath})") @Options(useGeneratedKeys=true,keyProperty="id") void insertReply(Map<String,Object> reply);
    @Update("UPDATE replies SET status='deleted' WHERE id=#{id}") void deleteReply(long id);
    @Update("UPDATE replies SET is_accepted=TRUE WHERE id=#{id}") void acceptReply(long id);
    @Update("UPDATE posts SET is_solved=TRUE,accepted_reply_id=#{replyId} WHERE id=#{postId} AND accepted_reply_id IS NULL") int acceptPost(@Param("postId") long postId,@Param("replyId") long replyId);
    @Select("SELECT COUNT(*) FROM replies WHERE post_id=#{postId} AND author_id=#{userId} AND status='published'") int priorReply(@Param("postId") long postId,@Param("userId") long userId);
    @Insert("INSERT IGNORE INTO favorites(user_id,post_id) VALUES(#{userId},#{postId})") void favorite(@Param("userId") long userId,@Param("postId") long postId);
    @Delete("DELETE FROM favorites WHERE user_id=#{userId} AND post_id=#{postId}") void unfavorite(@Param("userId") long userId,@Param("postId") long postId);
    @Select("SELECT COUNT(*) FROM favorites WHERE user_id=#{userId} AND post_id=#{postId}") int isFavorite(@Param("userId") long userId,@Param("postId") long postId);
    @Select("SELECT p.id,p.title,p.type,p.created_at,b.name AS board_name FROM favorites f JOIN posts p ON p.id=f.post_id JOIN boards b ON b.id=p.board_id WHERE f.user_id=#{userId} AND p.status='published' ORDER BY f.post_id DESC LIMIT #{limit} OFFSET #{offset}") List<Map<String,Object>> favorites(@Param("userId") long userId,@Param("limit") int limit,@Param("offset") int offset);
    @Insert("INSERT INTO notifications(user_id,kind,message,post_id) VALUES(#{userId},#{kind},#{message},#{postId})") void notifyUser(@Param("userId") long userId,@Param("kind") String kind,@Param("message") String message,@Param("postId") Long postId);
    @Select("SELECT * FROM notifications WHERE user_id=#{userId} ORDER BY created_at DESC LIMIT 100") List<Map<String,Object>> notifications(long userId);
    @Select("SELECT COUNT(*) FROM notifications WHERE user_id=#{userId} AND is_read=FALSE") int unread(long userId);
    @Update("UPDATE notifications SET is_read=TRUE WHERE id=#{id} AND user_id=#{userId}") void read(@Param("userId") long userId,@Param("id") long id);
    @Update("UPDATE notifications SET is_read=TRUE WHERE user_id=#{userId}") void readAll(long userId);
    @Select("SELECT COUNT(*) FROM point_logs WHERE user_id=#{userId} AND action=#{action} AND DATE(created_at)=CURRENT_DATE()") int dailyPoints(@Param("userId") long userId,@Param("action") String action);
    @Select("SELECT COUNT(*) FROM point_logs WHERE user_id=#{userId} AND action=#{action} AND ref_type=#{refType} AND ref_id=#{refId}") int rewardExists(@Param("userId") long userId,@Param("action") String action,@Param("refType") String refType,@Param("refId") long refId);
    @Update("UPDATE users SET points=GREATEST(0,points+#{amount}) WHERE id=#{userId}") void addPoints(@Param("userId") long userId,@Param("amount") int amount);
    @Select("SELECT points FROM users WHERE id=#{id}") int points(long id);
    @Insert("INSERT INTO point_logs(user_id,action,points,balance_after,ref_type,ref_id) VALUES(#{userId},#{action},#{amount},#{balance},#{refType},#{refId})") void pointLog(@Param("userId") long userId,@Param("action") String action,@Param("amount") int amount,@Param("balance") int balance,@Param("refType") String refType,@Param("refId") Long refId);
    @Select("SELECT * FROM point_logs WHERE user_id=#{userId} ORDER BY id DESC LIMIT 100") List<Map<String,Object>> pointLogs(long userId);
    @Select("SELECT COUNT(*) FROM reports WHERE reporter_id=#{userId} AND DATE(created_at)=CURRENT_DATE()") int dailyReports(long userId);
    @Insert("INSERT INTO reports(reporter_id,target_type,target_id,reason,description) VALUES(#{userId},#{type},#{targetId},#{reason},#{description})") void report(@Param("userId") long userId,@Param("type") String type,@Param("targetId") long targetId,@Param("reason") String reason,@Param("description") String description);
    @Select("SELECT * FROM reports WHERE id=#{id}") Map<String,Object> reportById(long id);
    @Select("SELECT r.*,u.username AS reporter_name FROM reports r JOIN users u ON u.id=r.reporter_id ORDER BY (r.status='pending') DESC,r.id DESC LIMIT 100") List<Map<String,Object>> reports();
    @Update("UPDATE reports SET status=#{status},handler_id=#{handler},handle_note=#{note},handled_at=NOW() WHERE id=#{id} AND status='pending'") int handleReport(@Param("id") long id,@Param("status") String status,@Param("handler") long handler,@Param("note") String note);
    @Update("UPDATE posts SET is_featured=#{featured} WHERE id=#{id} AND is_featured != #{featured}") int feature(@Param("id") long id,@Param("featured") boolean featured);
    @Update("UPDATE posts SET is_top=#{top} WHERE id=#{id}") void top(@Param("id") long id,@Param("top") boolean top);
    @Update("UPDATE users SET status=#{status} WHERE id=#{id}") void userStatus(@Param("id") long id,@Param("status") String status);
    @Update("UPDATE users SET role=#{role},moderator_board_id=#{boardId} WHERE id=#{id}") void userRole(@Param("id") long id,@Param("role") String role,@Param("boardId") Long boardId);
    @Select("SELECT id,email,username,role,status,moderator_board_id,points,created_at FROM users ORDER BY id DESC LIMIT 100") List<Map<String,Object>> users();
    @Select("SELECT id FROM users") List<Long> allUserIds();
    @Select("SELECT p.id,p.title,p.status,p.is_featured,p.is_top,p.board_id,p.created_at,u.username FROM posts p JOIN users u ON u.id=p.author_id ORDER BY p.id DESC LIMIT 100") List<Map<String,Object>> adminPosts();
    @Select("SELECT (SELECT COUNT(*) FROM users) AS users,(SELECT COUNT(*) FROM posts WHERE status='published') AS posts,(SELECT COUNT(*) FROM replies WHERE status='published') AS replies,(SELECT COUNT(*) FROM posts WHERE DATE(created_at)=CURRENT_DATE()) AS today,(SELECT COUNT(*) FROM reports WHERE status='pending') AS pending") Map<String,Object> dashboard();
    @Insert("INSERT INTO admin_logs(actor_id,action,target_type,target_id,detail) VALUES(#{actor},#{action},#{type},#{target},#{detail})") void adminLog(@Param("actor") long actor,@Param("action") String action,@Param("type") String type,@Param("target") long target,@Param("detail") String detail);
    @Select("SELECT * FROM admin_logs ORDER BY id DESC LIMIT 100") List<Map<String,Object>> adminLogs();
    @Insert("INSERT INTO boards(name,slug,description,sort_order) VALUES(#{name},#{slug},#{description},#{sortOrder})") void addBoard(@Param("name") String name,@Param("slug") String slug,@Param("description") String description,@Param("sortOrder") int sortOrder);
    @Select("SELECT id,name,status FROM boards WHERE id=#{id}") Map<String,Object> adminBoard(long id);
    @Update("UPDATE boards SET status='disabled' WHERE id=#{id} AND status='enabled'") int disableBoard(long id);
    @Insert("INSERT INTO tags(name) VALUES(#{name})") void addTag(String name);
    @Select("SELECT id,name,status FROM tags WHERE id=#{id}") Map<String,Object> adminTag(long id);
    @Update("UPDATE tags SET status='disabled' WHERE id=#{id} AND status='enabled'") int disableTag(long id);
    @Select("SELECT id,username,points,school,grade,public_school,public_grade FROM users WHERE id=#{id}") Map<String,Object> publicUser(long id);
    @Select("SELECT COUNT(*) FROM users WHERE email=#{email}") int emailExists(String email);
    @Insert("INSERT INTO users(email,username,password_hash,role,moderator_board_id,points) VALUES(#{email},#{username},#{hash},#{role},#{boardId},5)") void demoUser(@Param("email") String email,@Param("username") String username,@Param("hash") String hash,@Param("role") String role,@Param("boardId") Long boardId);
}
