-- 硬删除帖子：把 posts 的三条子表外键改成 ON DELETE CASCADE，
-- 之后删除 posts 一行就会自动清掉 replies / post_tags / favorites，应用层不用逐个删。
-- 约束名从 information_schema 动态查出来再删，不依赖 MySQL 的自动命名（ibfk_N）。
-- 这段写法是幂等的：重复执行只会把同一条外键重建为级联版本。
SET @fk = (SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='replies' AND COLUMN_NAME='post_id' AND REFERENCED_TABLE_NAME='posts' LIMIT 1);
SET @sql = IF(@fk IS NULL, 'SELECT 1', CONCAT('ALTER TABLE replies DROP FOREIGN KEY `', @fk, '`')); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
ALTER TABLE replies ADD CONSTRAINT replies_post_fk FOREIGN KEY(post_id) REFERENCES posts(id) ON DELETE CASCADE;

SET @fk = (SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='post_tags' AND COLUMN_NAME='post_id' AND REFERENCED_TABLE_NAME='posts' LIMIT 1);
SET @sql = IF(@fk IS NULL, 'SELECT 1', CONCAT('ALTER TABLE post_tags DROP FOREIGN KEY `', @fk, '`')); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
ALTER TABLE post_tags ADD CONSTRAINT post_tags_post_fk FOREIGN KEY(post_id) REFERENCES posts(id) ON DELETE CASCADE;

SET @fk = (SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='favorites' AND COLUMN_NAME='post_id' AND REFERENCED_TABLE_NAME='posts' LIMIT 1);
SET @sql = IF(@fk IS NULL, 'SELECT 1', CONCAT('ALTER TABLE favorites DROP FOREIGN KEY `', @fk, '`')); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
ALTER TABLE favorites ADD CONSTRAINT favorites_post_fk FOREIGN KEY(post_id) REFERENCES posts(id) ON DELETE CASCADE;
